### ISSUE TITLE
Fails to find nsig function

### ISSUE THREAD

**Issue by fpletz** [iv-org/inv_sig_helper#36] opened 2024-12-09 18:21 UTC
Tried with different source IPs (residential, data center, VPN) and environments (NixOS, official Docker image).

Log:
```
[2024-12-09T18:16:24Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-09T18:16:25Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
[2024-12-09T18:16:25Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
thread 'main' panicked at src/player.rs:150:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MrLego8-9** [comment] 2024-12-09 18:44
Complete trace
```
inv_sig_helper-1  | [2024-12-09T18:15:58Z INFO  inv_sig_helper_rust] Fetching player
inv_sig_helper-1  | [2024-12-09T18:15:59Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
inv_sig_helper-1  | [2024-12-09T18:15:59Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
inv_sig_helper-1  | thread 'main' panicked at src/player.rs:150:10:
inv_sig_helper-1  | called `Option::unwrap()` on a `None` value
inv_sig_helper-1  | stack backtrace:
inv_sig_helper-1  |    0:     0x768bf86ea0f1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h706c9783aace6373
inv_sig_helper-1  |    1:     0x768bf85467fb - core::fmt::write::h7221bf2763310748
inv_sig_helper-1  |    2:     0x768bf86c3ce2 - std::io::Write::write_fmt::h5f543a3ea7d45c3d
inv_sig_helper-1  |    3:     0x768bf86ef269 - std::sys_common::backtrace::print::hf2079bcf21b5d607
inv_sig_helper-1  |    4:     0x768bf86eea56 - std::panicking::default_hook::{{closure}}::hd6a41ed4ba4d9cdd
inv_sig_helper-1  |    5:     0x768bf86efe61 - std::panicking::rust_panic_with_hook::he62aa99a29ab1fe6
inv_sig_helper-1  |    6:     0x768bf86ef59a - std::panicking::begin_panic_handler::{{closure}}::h4295830cbed5c147
inv_sig_helper-1  |    7:     0x768bf86ef529 - std::sys_common::backtrace::__rust_end_short_backtrace::h29724adceafc0e2c
inv_sig_helper-1  |    8:     0x768bf86ef516 - rust_begin_unwind
inv_sig_helper-1  |    9:     0x768bf84c0192 - core::panicking::panic_fmt::h5822797b7c57c9a6
inv_sig_helper-1  |   10:     0x768bf84c032b - core::panicking::panic::h576d2b304e82d017
inv_sig_helper-1  |   11:     0x768bf84c06e8 - core::option::unwrap_failed::hf12f69fdafb5c188
inv_sig_helper-1  |   12:     0x768bf84fdc7e - inv_sig_helper_rust::player::fetch_update::{{closure}}::h61359dd4904a6910
inv_sig_helper-1  |   13:     0x768bf8516c18 - inv_sig_helper_rust::main::{{closure}}::h92460df08abff2f1
inv_sig_helper-1  |   14:     0x768bf850ddca - inv_sig_helper_rust::main::h4c6ed7911b8effb7
inv_sig_helper-1  |   15:     0x768bf84d58c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65fca62ed9181c86
inv_sig_helper-1  |   16:     0x768bf851a154 - main
```

**Comment by rudism** [comment] 2024-12-09 19:03
Looks like YT changed something that breaks the regex that extracts the nsig function. youtube-dl and yt-dlp facing/faced similar issues in the past few days:
- https://github.com/ytdl-org/youtube-dl/issues/32986
- https://github.com/yt-dlp/yt-dlp/issues/11744

**Comment by unixfox** [comment] 2024-12-09 19:52
YouTube.js seems affected too: https://github.com/LuanRT/YouTube.js/issues/831

**Comment by shatrix** [comment] 2024-12-09 20:23
same here:
```
thread 'main' panicked at src/player.rs:150:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gabe4278** [comment] 2024-12-09 20:40
got a similar problem, most invidious backends were down due to YouTube's recent update

my instance is hosted on Arch Linux, invidious is ok, signature keeps throwing an error saying `nsig function ending did not work`, then throws an error:
```
thread 'main' panicked at src/player.rs:150:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: inv_sig_helper_rust::player::fetch_update::{{closure}}
   5: inv_sig_helper_rust::main::{{closure}}
   6: inv_sig_helper_rust::main
```

full backtrace:
```
   0:     0x627f4cafd099 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6214d82a5df2595e
   1:     0x627f4c94696b - core::fmt::write::hf5f42bf308c7c107
   2:     0x627f4cad1982 - std::io::Write::write_fmt::h6df9e7e82894c66e
   3:     0x627f4cb01c07 - std::panicking::default_hook::{{closure}}::h1126899e8fa68624
   4:     0x627f4cb02e6f - std::panicking::rust_panic_with_hook::hb0baad225caa9be4
   5:     0x627f4cb026a2 - std::panicking::begin_panic_handler::{{closure}}::ha222a98a0f4c074b
   6:     0x627f4cb02639 - std::sys::backtrace::__rust_end_short_backtrace::haf27a742036be4a5
   7:     0x627f4cb02624 - rust_begin_unwind
   8:     0x627f4c8c4522 - core::panicking::panic_fmt::h2c68b1b94dbf98c7
   9:     0x627f4c8c45db - core::panicking::panic::h32fe1c1fe6035a54
  10:     0x627f4c8c4998 - core::option::unwrap_failed::h9c9d9ca460059c56
  11:     0x627f4c8fd26b - inv_sig_helper_rust::player::fetch_update::{{closure}}::hfee4fed1ad16513e
  12:     0x627f4c914a93 - inv_sig_helper_rust::main::{{closure}}::hd6936f9251c7e076
  13:     0x627f4c90d67a - inv_sig_helper_rust::main::hcc3a4ad7b45c58fe
  14:     0x627f4c8d4d63 - std::sys::backtrace::__rust_begin_short_backtrace::he8c6eb728494bc2f
  15:     0x627f4c9188a2 - main
  16:     0x79a560e34e08 - <unknown>
  17:     0x79a560e34ecc - __libc_start_main
  18:     0x627f4c8d3065 - _start
  19:                0x0 - <unknown>
```

would this problem be fixed asap?

**Comment by unixfox** [comment] 2024-12-09 20:50
Like with every bug report. Please comment only if you have new things to bring on. Thank you.

**Comment by lifo9** [comment] 2024-12-09 23:54
I've tried to create [a patch](https://0x0.st/XhpN.patch) using `yt-dlp` fixes([1](https://github.com/yt-dlp/yt-dlp/pull/11751/files), [2](https://github.com/yt-dlp/yt-dlp/pull/11750/files)).
It seems that signature helper is now working:

```
...
[2024-12-09T23:43:20Z DEBUG inv_sig_helper_rust::player] got nsig fn code: function decrypt_nsig(J){var R=J.split(J.slice(0,0)),...
[2024-12-09T23:43:20Z INFO  inv_sig_helper_rust::player] sig code: var pen;var Gw={s9:function(J,R){J.splice(0,R)},Az:function(J,R){var N=J[0];J[0]=J[R%J.length];J[R%J.length]=N},hp:function(J){J.reverse()}};pen=function(J){J=J.split("");Gw.Az(J,29);Gw.s9(J,3);Gw.Az(J,43);Gw.Az(J,11);Gw.s9(J,3);Gw.Az(J,3);Gw.Az(J,34);return J.join("")}
[2024-12-09T23:43:20Z INFO  inv_sig_helper_rust] Successfully fetched player
...
```

But on the video page I get the following error:
```
The media could not be loaded, either because the server or network failed or because the format is not supported.
```
and the request to `/videoplayback` fails with 403 error.
<img width="870" alt="image" src="https://github.com/user-attachments/assets/b8e2eb0a-0b3a-4817-894a-d47a1cc50edd">

**Comment by lifo9** [comment] 2024-12-10 00:25
I think I've got a fix 🎉
https://0x0.st/XhpM.patch

**Comment by rockerBOO** [comment] 2024-12-10 00:35
Can confirm it's playing videos with the patch from lifo9. I made a [container](https://hub.docker.com/r/rockerboo/inv_sig_helper) for it until an official release is available.

**Comment by ggtylerr** [comment] 2024-12-10 00:48
Confirmed working - Have it on both of my servers, CAL-1 and POL-1, and videos seem to work fine. Thank you @lifo9 and @rockerBOO !

**Comment by iGerman00** [comment] 2024-12-10 02:06
@rockerBOO any chance you could add an arm64 arch to your container?

**Comment by johnpc** [comment] 2024-12-10 04:03
@rockerBOO can you build for aarch64

**Comment by rockerBOO** [comment] 2024-12-10 04:32
@iGerman00 @johnpc i don't know how to, the docker file seems to use the host architecture to build it so --platform isn't enough

  > [user-stage 2/2] RUN adduser -u 10001 -S appuser:
0.190 exec /bin/sh: exec format error

**Comment by johnpc** [comment] 2024-12-10 04:41
If you forked the project, it should be enough to update the `.github` configuration but update the dockerhub/quay image name and credentials. It would then build and publish for all architectures. https://github.com/iv-org/inv_sig_helper/blob/master/.github/workflows/docker-build-push.yaml#L20

GitHub Actions free tier is quite generous.

I get that it's a pain though, so I understand if you don't wanna deal with tit. I'm sure someone will PR that diff and it'll be merged soon enough.

**Comment by unixfox** [comment] 2024-12-10 06:41
@lifo9 feel free to send a PR even if it's not that clean.

**Comment by rockerBOO** [comment] 2024-12-10 06:48
@iGerman00 @johnpc https://hub.docker.com/r/rockerboo/inv-sig-helper should have arm on it now (different name than the other one)

**Comment by unixfox** [comment] 2024-12-10 09:23
Fixed in https://github.com/iv-org/inv_sig_helper/commit/ac0269f1586df5a853c4321256866bcbea89802b

**Closed by unixfox** 2024-12-10 09:23 UTC
Labels: bug

**Comment by rudism** [comment] 2024-12-11 14:03
@CDSWambo `docker compose pull` will fetch the new image. Then `docker compose up -d --force-recreate` will replace your current running image with the new version.

**Comment by itsbumblebeecode** [comment] 2024-12-16 17:10
i've git the same error

**Comment by Wyrrrd** [comment] 2024-12-16 17:41
Being on latest, it worked for last week, but the bug returned around 5min ago...

```
[2024-12-16T17:37:55Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-16T17:37:56Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
[2024-12-16T17:37:56Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
thread 'main' panicked at src/player.rs:185:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by predecker** [comment] 2024-12-16 17:45
same here.

**Comment by RobinBoers** [comment] 2024-12-16 17:45
Same issue here, also on latest

**Comment by uncaney** [comment] 2024-12-16 17:55
same
