### ISSUE TITLE
nsig function ending did not work:

### ISSUE THREAD

**Issue by manfromdownunder** [iv-org/inv_sig_helper#27] opened 2024-09-27 13:46 UTC
Does the regex need to be updated in consts.rs for the latest base.js? Or am I doing something wrong?  

Error: 
```
WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
inv_sig_helper-1  | [2024-09-27T13:33:52Z INFO  inv_sig_helper_rust::player] sig code: var iCa;var kL={nx:function(a,b){a.splice(0,b)},
inv_sig_helper-1  |     Wq:function(a){a.reverse()},
inv_sig_helper-1  |     FT:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}};iCa=function(a){a=a.split("");kL.Wq(a,30);kL.nx(a,3);kL.Wq(a,4);kL.nx(a,3);kL.FT(a,29);kL.nx(a,1);kL.FT(a,8);kL.FT(a,66);kL.nx(a,2);return a.join("")}
inv_sig_helper-1  | [2024-09-27T13:33:52Z INFO  inv_sig_helper_rust] Successfully fetched player
```

**Comment by unixfox** [comment] 2024-09-27 13:56
duplicate of https://github.com/iv-org/inv_sig_helper/issues/18

**Closed by unixfox** 2024-09-27 13:56 UTC
